--
-- SPDX-License-Identifier: BSD-2-Clause
--
-- Copyright (c) 2023 Warner Losh <imp@FreeBSD.org>
--

--
-- Data format is a little strange. The ATA standards don't really define a byte
-- order. The dtrace script reports things out of the kernel in FreeBSD ata_cmd
-- byte order, which is weird. These tables assume that the array we're looking
-- at is in the following byte order, big endian. This makes it easiest to decode
--
-- +======+===================+=====================+
-- | Byte | Field             | FreeBSD ata_cmd     |
-- +======+===================+=====================+
-- |    0 | COMMAND           | command           1 | ata_cmd.flags reported, but
-- +------+-------------------+---------------------+ not copied to this table.
-- |    1 | FEATURES      MSB | features_exp     10 |
-- |    2 |               LSB | features          2 |
-- +------+-------------------+---------------------+
-- |    3 | LBA           MSB | lba_high_exp      9 |
-- |    4 |                   | lba_mid_exp       8 |
-- |    5 |                   | lba_low_exp       7 |
-- |    6 |                   | lba_high          5 |
-- |    7 |                   | lba_mid           4 |
-- |    8 |               LSB | lba_low           3 |
-- +------+-------------------+---------------------+
-- |    9 | SECTOR COUNT  MSB | sector_count_exp 12 |
-- |   10 |               LSB | sector_count     11 |
-- +------+-------------------+---------------------+
-- |   11 | DEVICE            | device            6 |
-- +------+-------------------+---------------------+
-- |   12 | CONTROL           | control          13 |
-- +------+-------------------+---------------------+
-- |   13 | ISS               | <iss>            14 | not really in ata_cmd, but
-- +------+-------------------+---------------------+ these bytes are reported out
-- |   14 | AUX           MSB | <aux>            15 | as if they were in ata_cmd
-- |   15 |                   |                  16 | at the end. The XPT_ATA_IO
-- |   16 |                   |                  17 | CCB has them oddly located
-- |   17 |               LSB |                  18 | for compat reasons.
-- +======+===================+=====================+
--
-- So all the entries below should specify 'byte' offsets, plus all the
-- fields to report.
--
-- This also lets us report differently for 28 vs 48 bit commands.
--
-- The filtering of ata_all.c assumed that all fields are always valid. This is
-- not quite right, and will need to be manually adjusted.
--

local ata_io = {
    {
	name="NOP FLUSHQUEUE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x00, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x00, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NOP AUTOPOLL", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x00, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NOP", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x00, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CFA REQUEST EXTENDED ERROR", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x03, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DSM TRIM",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x06, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DSM",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x06, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DSM XL TRIM",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x07, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DSM XL",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x07, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE RESET", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x08, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="REQUEST SENSE DATA EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x0b, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="GET PHYSICAL ELEMENT STATUS",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x12, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x20, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ NO RETRY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x21, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ LONG", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x22, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ LONG NO RETRY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x23, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x24, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ DMA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x25, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ DMA QUEUED48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x26, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ NATIVE MAX ADDRESS48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x27, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ MUL48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x29, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ STREAM DMA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x2a, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ STREAM48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x2b, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ LOG EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x2f, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x30, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE NO RETRY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x31, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE LONG", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x32, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE LONG NO RETRY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x33, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x34, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x35, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA QUEUED48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x36, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX ADDRESS48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x37, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CFA WRITE SECTORS WITHOUT ERASE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x38, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE MUL48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x39, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE STREAM DMA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3a, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE STREAM48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3b, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE VERIFY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3c, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA FUA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3d, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA QUEUED FUA48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3e, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE LOG EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x3f, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ VERIFY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x40, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ VERIFY NO RETRY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x41, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ VERIFY48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x42, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ZERO EXT TRIM",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x44, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ZERO EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x44, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE UNCORRECTABLE48 PSEUDO",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x45, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x55, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE UNCORRECTABLE48 FLAGGED",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x45, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0xaa, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE UNCORRECTABLE48",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x45, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ LOG DMA EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x47, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ZAC MANAGEMENT IN",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x4a, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="FORMAT TRACK", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x50, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CONFIGURE STREAM",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x51, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE LOG DMA EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x57, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="TRUSTED NON DATA", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x5b, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="TRUSTED RECEIVE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x5c, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="TRUSTED RECEIVE DMA", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x5d, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="TRUSTED SEND", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x5e, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="TRUSTED SEND DMA", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x5f, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ FPDMA QUEUED",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x60, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE FPDMA QUEUED",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x61, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA ABORT NCQ QUEUE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x00, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA DEADLINE HANDLING",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA HYBRID DEMOTE BY SIZE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x02, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA HYBRID CHANGE BY LBA RANGE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x03, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA HYBRID CONTROL",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x04, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA SET FEATURES",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x05, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA ZERO EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x06, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA ZAC MANAGEMENT OUT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x07, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NCQ NON DATA",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x63, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED DATA SET MANAGEMENT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x00, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED HYBRID EVICT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED WRITE LOG DMA EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x02, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED ZAC MANAGEMENT OUT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x03, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED DATA SET MANAGEMENT XL",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x04, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEND FPDMA QUEUED",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x64, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="RECEIVE FPDMA QUEUED READ LOG DMA EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x65, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="RECEIVE FPDMA QUEUED ZAC MANAGEMENT IN",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x65, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x02, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="RECEIVE FPDMA QUEUED",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x65, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN IDENTIFY",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURE", len=8, byte=1, bit=0, id=true, value=0xec, },
	{ name="LBA", len=24, byte=6, bit=0, level=1 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0, level=1 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN READ BUFFER",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURES", len=8, byte=2, bit=0, level=1, },
	{ name="LBA_MSB", len=16, byte=6, bit=0, level=1 },
	{ name="LBA_LOW", len=8, byte=8, bit=0, id=true, value=0x00, },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN RECEIVE DIAGNOSTIC RESULTS",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURES", len=8, byte=2, bit=0, level=1, },
	{ name="LBA_MSB", len=16, byte=6, bit=0, level=1 },
	{ name="LBA_LOW", len=8, byte=8, bit=0, id=true, value=0x02, },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN WRITE BUFFER",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURES", len=8, byte=2, bit=0, level=1, },
	{ name="LBA_MSB", len=16, byte=6, bit=0, level=1 },
	{ name="LBA_LOW", len=8, byte=8, bit=0, id=true, value=0x80, },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN SEND DIAGNOSTIC",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURES", len=8, byte=2, bit=0, level=1, },
	{ name="LBA_MSB", len=16, byte=6, bit=0, level=1 },
	{ name="LBA_LOW", len=8, byte=8, bit=0, id=true, value=0x82, },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEP ATTN",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x67, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SEEK", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x70, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET DATE TIME EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x77, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="GET NATIVE MAX ADDRESS EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x78, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x00, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET ACCESSIBLE MAX ADDRESS EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x78, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="FREEZE ACCESSIBLE MAX ADDRESS EXT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x78, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x02, },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ACCESSIBLE MAX ADDRESS CONFIGURATION",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x78, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="REMOVE ELEMENT AND TRUNCATE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x7c, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CFA TRANSLATE SECTOR",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x87, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="EXECUTE DEVICE DIAGNOSTIC", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x90, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="INITIALIZE DEVICE PARAMETERS", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x91, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE TEMPORARY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x01, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE SAVE WITH OFFSET", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x03, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE SAVE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x07, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE SAFE FOR FUTURE USE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x0e, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE ACTIVATE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURES", len=8, byte=2, bit=0, id=true, value=0x0f, },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x92, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DOWNLOAD MICROCODE DMA", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x93, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="STANDBY IMMEDIATE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x94, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="IDLE IMMEDIATE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x95, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="STANDBY",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x96, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="IDLE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x97, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CHECK POWER MODE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x98, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SLEEP",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x99, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ZAC MANAGEMENT OUT",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0x9a, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="PACKET", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xa0, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ATAPI IDENTIFY", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xa1, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SERVICE", is28=true,
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xa2, },
	{ name="FEATURE", len=8, byte=2, bit=0 },
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART READ ATTR VALUES",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd0, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART READ ATTR THRESHOLDS",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd1, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART ENABLE/DISABLE ATTRIBUTE AUTOSAVE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd2, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART SAVE ATTR VALUES",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd3, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART EXECUTE OFFLINE IMMEDIATE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd4, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART READ LOG",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd5, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART WRITE LOG",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd6, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART ATTRIBUTE THRESHOLDS",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd7, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART ENABLE OPERATION",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd8, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART DISABLE OPERATION",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xd9, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART RETURN STATUS",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xda, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART ENABLE/DISABLE AUTO OFFLINE",
	{ name="COMMAND", len=8, byte=0, bit=0, id=true, value=0xdb, },
	{ name="FEATURE", len=16, byte=1, bit=0 },
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SMART",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE CONFIGURATION RESTORE",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE CONFIGURATION FREEZE LOCK",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE CONFIGURATION IDENTIFY",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE CONFIGURATION SET",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="DEVICE CONFIGURATION",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET SECTOR CONFIGURATION EXT", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SANITIZE STATUS EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CRYPTO SCRAMBLE EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="BLOCK ERASE EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="OVERWRITE EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SANITIZE FREEZE LOCK EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SANITIZE ANTIFREEZE LOCK EXT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SANITIZE DEVICE",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="NV CACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CFA ERASE",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ MUL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE MUL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MULTI", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ DMA QUEUED", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ DMA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA NO RETRY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE DMA QUEUED", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CFA WRITE MULTIPLE WITHOUT ERASE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE MUL FUA48",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CHECK MEDIA CARD TYPE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="GET MEDIA STATUS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ACKNOWLEDGE MEDIA CHANGE",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="BOOT POST-BOOT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="BOOT PRE-BOOT",
	{ name="LBA", len=48, byte=3, bit=0 },
	{ name="SECTOR COUNT", len=16, byte=9, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="MEDIA LOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="MEDIA UNLOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="STANDBY IMMEDIATE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="IDLE IMMEDIATE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="STANDBY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="IDLE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ BUFFER/PM", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="CHECK POWER MODE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SLEEP", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="FLUSHCACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE BUFFER/PM", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ BUFFER DMA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="FLUSHCACHE48", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="WRITE BUFFER DMA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="ATA IDENTIFY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="MEDIA EJECT", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE 8BIT PIO", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE WCACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET TRANSFER MODE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE APM", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE PUIS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SPIN-UP", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE CFA POWER MODE 1", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE WRITE READ VERIFY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE DEVICE LIFE CONTROL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE SATA FEATURE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET TIME LIMITED R/W WCT", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET TIME LIMITED R/W EH", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE MEDIA STATIS NOTIFICATION", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE RETRY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE FREEFALL CONTROL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE AAM", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET MAX HOST INT SECT TIMES", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES LENGTH OF VS DATA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET RATE BASIS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES EXTENDED POWER CONDITIONS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ADVANCED BACKGROUD OPERATION", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET CACHE SEGS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE RCACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE RELIRQ", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE SRVIRQ", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES LONG PHYS SECT ALIGN ERC", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DSN", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE DEFAULTS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES LPS ERROR REPORTING CONTROL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE ECC", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE 8BIT PIO", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE WCACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE APM", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE PUIS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE ECC", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE CFA POWER MODE 1", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE WRITE READ VERIFY", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE DEVICE LIFE CONTROL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE SATA FEATURE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE MEDIA STATUS NOTIFICATION", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE RETRIES", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET MAX AVERAGE CURR", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE RCACHE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SET MAX PREFETCH", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES 4 BYTE VS DATA", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE FREEFALL CONTROL", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES SENSE DATA REPORTING", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES NCQ SENSE DATA RETURN", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES ENABLE DEFAULTS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE RELIRQ", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES DISABLE SRVIRQ", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES Vendor Specific", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SETFEATURES", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY SET PASSWORD", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY UNLOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY ERASE PREPARE", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY ERASE UNIT", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY FREEZE LOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SECURITY DISABLE PASSWORD", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="READ NATIVE MAX ADDRESS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX ADDRESS", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX SET PASSWORD", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX LOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX UNLOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX FREEZE LOCK", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
    {
	name="SET MAX", is28=true,
	{ name="LBA", len=24, byte=6, bit=0 },
	{ name="SECTOR COUNT", len=8, byte=10, bit=0 },
	{ name="DEVICE", len=8, byte=11, bit=0, level=2 },
	{ name="CONTROL", len=8, byte=12, bit=0, level=2 },
    },
}

return ata_io
