--
-- SPDX-License-Identifier: BSD-2-Clause
--
-- Copyright (c) 2023 Warner Losh <imp@FreeBSD.org>
--

--
-- This file was generated from cdb-description.js, lightly edited to remove
-- some actual javascript wrapping and convert single quoted key names to
-- double, obtained from https://github.com/logical-paradox/scsi-cdb whose
-- license is MIT. The generated code was further modified and transformed by
-- the modification process. It is now maintained by hand because scsi-cdb is
-- not an active project. The project was by Garath John, but included no
-- copyright notice.
--
-- I augmented it with the SAT-5 definitions for SCSI passthrough of ATA
-- commands.
--
-- It might make sense to split these along the different standards and support
-- per-device type tracing, in which case some use of the op-code.txt file from
-- t10 might be in order.
--

local scsi_io = {
    {
	name="BIND",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xe, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="NRD", len=1, byte=2, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=2, bit=1, reserved=true, },
	{ name="Reserved", len=72, byte=3, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="CHANGE ALIASES",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xb, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="COPY OPERATION ABORT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x83, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x1c, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=2, bit=0, },
	{ name="Reserved", len=72, byte=6, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="COPY OPERATION CLOSE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x83, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x1d, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=2, bit=0, },
	{ name="IMMED", len=1, byte=6, bit=0, nonzero=true, },
	{ name="TO_MED", len=1, byte=6, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=6, bit=2, reserved=true, },
	{ name="Reserved", len=64, byte=7, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="EXTENDED COPY",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x83, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x1, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=64, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="INQUIRY",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x12, },
	{ name="EVPD", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="PAGE CODE", len=8, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=16, byte=3, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="LOG SELECT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x4c, },
	{ name="SP", len=1, byte=1, bit=0, nonzero=true, },
	{ name="PCR", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="PAGE CODE", len=6, byte=2, bit=3, nonzero=true, },
	{ name="PC", len=2, byte=2, bit=6, nonzero=true, },
	{ name="SUBPAGE CODE", len=8, byte=3, bit=0, },
	{ name="Reserved", len=24, byte=4, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="LOG SENSE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x4d, },
	{ name="SP", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="PAGE CODE", len=6, byte=2, bit=3, nonzero=true, },
	{ name="PC", len=2, byte=2, bit=6, nonzero=true, },
	{ name="SUBPAGE CODE", len=8, byte=3, bit=0, },
	{ name="Reserved", len=8, byte=4, bit=0, reserved=true, },
	{ name="PARAMETER POINTER", len=16, byte=5, bit=0, },
	{ name="ALLOCATION LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="MANAGEMENT PROTOCOL IN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x10, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="MANAGEMENT PROTOCOL", len=8, byte=2, bit=0, },
	{ name="MANAGEMENT PROTOCOL SPECIFIC1", len=24, byte=3, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="MANAGEMENT PROTOCOL SPECIFIC2", len=8, byte=10, bit=0, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="MANAGEMENT PROTOCOL OUT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x10, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="MANAGEMENT PROTOCOL", len=8, byte=2, bit=0, },
	{ name="MANAGEMENT PROTOCOL SPECIFIC1", len=24, byte=3, bit=0, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="MANAGEMENT PROTOCOL SPECIFIC2", len=8, byte=10, bit=0, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="MODE SELECT (6)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x15, },
	{ name="SP", len=1, byte=1, bit=0, nonzero=true, },
	{ name="RTD", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=2, byte=1, bit=2, reserved=true, },
	{ name="PF", len=1, byte=1, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=8, byte=4, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="MODE SELECT (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x55, },
	{ name="SP", len=1, byte=1, bit=0, nonzero=true, },
	{ name="RTD", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=2, byte=1, bit=2, reserved=true, },
	{ name="PF", len=1, byte=1, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=40, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="MODE SENSE (6)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x1a, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="DBD", len=1, byte=1, bit=3, nonzero=true, },
	{ name="Reserved", len=4, byte=1, bit=4, reserved=true, },
	{ name="PAGE CODE", len=6, byte=2, bit=0, nonzero=true, },
	{ name="PC", len=2, byte=2, bit=6, nonzero=true, },
	{ name="SUBPAGE CODE", len=8, byte=3, bit=0, },
	{ name="ALLOCATION LENGTH", len=8, byte=4, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="MODE SENSE (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x5a, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="DBD", len=1, byte=1, bit=3, nonzero=true, },
	{ name="LLBAA", len=1, byte=1, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="PAGE CODE", len=6, byte=2, bit=0, nonzero=true, },
	{ name="PC", len=2, byte=2, bit=6, nonzero=true, },
	{ name="SUBPAGE CODE", len=8, byte=3, bit=0, },
	{ name="Reserved", len=24, byte=4, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="PERSISTENT RESERVE IN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x5e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=40, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="PERSISTENT RESERVE OUT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x5f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="TYPE", len=4, byte=2, bit=0, nonzero=true, },
	{ name="SCOPE", len=4, byte=2, bit=4, nonzero=true, },
	{ name="Reserved", len=16, byte=3, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=5, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="PREPARE BINDING REPORT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xc, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=80, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="READ ATTRIBUTE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8c, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Restricted (see SMC-3)", len=24, byte=2, bit=0, },
	{ name="LOGICAL VOLUME NUMBER", len=8, byte=5, bit=0, },
	{ name="Reserved", len=8, byte=6, bit=0, reserved=true, },
	{ name="PARTITION NUMBER", len=8, byte=7, bit=0, },
	{ name="FIRST ATTRIBUTE IDENTIFIER", len=16, byte=8, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="READ BUFFER (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3c, },
	{ name="MODE", len=5, byte=1, bit=0, nonzero=true, },
	{ name="MODE SPECIFIC", len=3, byte=1, bit=5, nonzero=true, },
	{ name="BUFFER ID", len=8, byte=2, bit=0, },
	{ name="BUFFER OFFSET", len=24, byte=3, bit=0, },
	{ name="ALLOCATION LENGTH", len=24, byte=6, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="READ BUFFER (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9b, },
	{ name="MODE", len=5, byte=1, bit=0, nonzero=true, },
	{ name="MODE SPECIFIC", len=3, byte=1, bit=5, nonzero=true, },
	{ name="BUFFER OFFSET", len=64, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="BUFFER ID", len=8, byte=14, bit=0, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="READ MEDIA SERIAL NUMBER",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xab, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x1, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="RECEIVE BINDING REPORT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xf, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="BINDING LIST IDENTIFIER", len=32, byte=4, bit=0, },
	{ name="Reserved", len=32, byte=8, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="RECEIVE COPY DATA",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x84, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x6, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=2, bit=0, },
	{ name="Reserved", len=32, byte=6, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="RECEIVE COPY STATUS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x84, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x5, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=2, bit=0, },
	{ name="Reserved", len=32, byte=6, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="RECEIVE DIAGNOSTIC RESULTS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x1c, },
	{ name="PCV", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="PAGE CODE", len=8, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=16, byte=3, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="RECEIVE ROD TOKEN INFORMATION",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x84, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x7, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=2, bit=0, },
	{ name="Reserved", len=32, byte=6, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="RECEIVE I_T NEXUS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xc, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT ALIASES",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xb, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="RECEIVE ALL ROD TOKENS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x84, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x8, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=64, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="REPORT IDENTIFYING INFORMATION",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x5, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="Restricted (see SCC-2)", len=16, byte=4, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="IDENTIFYING INFORMATION TYPE", len=7, byte=10, bit=1, nonzero=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT LUNS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa0, },
	{ name="Reserved", len=8, byte=1, bit=0, reserved=true, },
	{ name="SELECT REPORT", len=8, byte=2, bit=0, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT PRIORITY",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xe, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=6, byte=2, bit=0, reserved=true, },
	{ name="PRIORITY REPORTED", len=2, byte=2, bit=6, nonzero=true, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT SUPPORTED OPERATION CODES",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xc, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="REPORTING OPTIONS", len=3, byte=2, bit=0, nonzero=true, },
	{ name="Reserved", len=4, byte=2, bit=3, reserved=true, },
	{ name="RCTD", len=1, byte=2, bit=7, nonzero=true, },
	{ name="REQUESTED OPERATION CODE", len=8, byte=3, bit=0, },
	{ name="REQUESTED SERVICE ACTION", len=16, byte=4, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT SUPPORTED TASK MANAGEMENT FUNCTIONS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xd, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=7, byte=2, bit=0, reserved=true, },
	{ name="REPD", len=1, byte=2, bit=7, nonzero=true, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT TARGET PORT GROUPS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xa, },
	{ name="PARAMETER DATA FORMAT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REPORT TIMESTAMP",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa3, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xf, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="REQUEST SENSE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3, },
	{ name="DESC", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=8, byte=4, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="SECURITY PROTOCOL IN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa2, },
	{ name="SECURITY PROTOCOL", len=8, byte=1, bit=0, },
	{ name="SECURITY PROTOCOL SPECIFIC", len=16, byte=2, bit=0, },
	{ name="Reserved", len=7, byte=4, bit=0, reserved=true, },
	{ name="INC_512", len=1, byte=4, bit=7, nonzero=true, },
	{ name="Reserved", len=8, byte=5, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SECURITY PROTOCOL OUT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xb5, },
	{ name="SECURITY PROTOCOL", len=8, byte=1, bit=0, },
	{ name="SECURITY PROTOCOL SPECIFIC", len=16, byte=2, bit=0, },
	{ name="Reserved", len=7, byte=4, bit=0, reserved=true, },
	{ name="INC_512", len=1, byte=4, bit=7, nonzero=true, },
	{ name="Reserved", len=8, byte=5, bit=0, reserved=true, },
	{ name="TRANSFER LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SEND DIAGNOSTIC",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x1d, },
	{ name="UNITOFFL", len=1, byte=1, bit=0, nonzero=true, },
	{ name="DEVOFFL", len=1, byte=1, bit=1, nonzero=true, },
	{ name="SELFTEST", len=1, byte=1, bit=2, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="PF", len=1, byte=1, bit=4, nonzero=true, },
	{ name="SELF-TEST CODE", len=3, byte=1, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=3, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="SET AFFILIATION",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xd, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=64, byte=2, bit=0, reserved=true, },
	{ name="Reserved", len=16, byte=10, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="SET IDENTIFYING INFORMATION",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x6, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="Restricted (see SCC-2)", len=16, byte=4, bit=0, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="IDENTIFYING INFORMATION TYPE", len=7, byte=10, bit=1, nonzero=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SET PRIORITY",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xe, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=6, byte=2, bit=0, reserved=true, },
	{ name="I_T_L NEXUS TO SET", len=2, byte=2, bit=6, nonzero=true, },
	{ name="Reserved", len=24, byte=3, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SET TARGET PORT GROUPS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xa, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SET TIMESTAMP",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa4, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xf, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="TEST BIND",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xb, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=80, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="TEST UNIT READY",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x0, },
	{ name="Reserved", len=32, byte=1, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="UNBIND",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0xf, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="ALL CONG", len=1, byte=2, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=2, bit=1, reserved=true, },
	{ name="Reserved", len=72, byte=3, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=12, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE ATTRIBUTE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8d, },
	{ name="WTC", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="Restricted (see SMC-3)", len=24, byte=2, bit=0, },
	{ name="LOGICAL VOLUME NUMBER", len=8, byte=5, bit=0, },
	{ name="Reserved", len=8, byte=6, bit=0, reserved=true, },
	{ name="PARTITION NUMBER", len=8, byte=7, bit=0, },
	{ name="Reserved", len=16, byte=8, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE BUFFER",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3b, },
	{ name="MODE", len=5, byte=1, bit=0, nonzero=true, },
	{ name="MODE SPECIFIC", len=3, byte=1, bit=5, nonzero=true, },
	{ name="BUFFER ID", len=8, byte=2, bit=0, },
	{ name="BUFFER OFFSET", len=24, byte=3, bit=0, },
	{ name="PARAMETER LIST LENGTH", len=24, byte=6, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="BACKGROUND CONTROL",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x15, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=6, byte=2, bit=0, reserved=true, },
	{ name="BO_CTL", len=2, byte=2, bit=6, nonzero=true, },
	{ name="BO_TIME", len=8, byte=3, bit=0, },
	{ name="Reserved", len=88, byte=4, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="COMPARE AND WRITE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x89, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="Reserved", len=24, byte=10, bit=0, reserved=true, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=8, byte=13, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="FORMAT UNIT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x4, },
	{ name="DEFECT LIST FORMAT", len=3, byte=1, bit=0, nonzero=true, },
	{ name="CMPLST", len=1, byte=1, bit=3, nonzero=true, },
	{ name="FMTDATA", len=1, byte=1, bit=4, nonzero=true, },
	{ name="LONGLIST", len=1, byte=1, bit=5, nonzero=true, },
	{ name="FMTPINFO", len=2, byte=1, bit=6, nonzero=true, },
	{ name="Vendor specific", len=8, byte=2, bit=0, },
	{ name="Reserved", len=16, byte=3, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="GET LBA STATUS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x12, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="STARTING LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="GET STREAM STATUS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x16, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="STARTING STREAM IDENTIFIER", len=16, byte=4, bit=0, },
	{ name="Reserved", len=32, byte=6, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="ORWRITE (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8b, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="ORPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="ORWRITE (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="BMOP", len=3, byte=2, bit=0, nonzero=true, },
	{ name="Reserved", len=5, byte=2, bit=3, reserved=true, },
	{ name="PREVIOUS GENERATION PROCESSING", len=4, byte=3, bit=0, nonzero=true, },
	{ name="Reserved", len=4, byte=3, bit=4, reserved=true, },
	{ name="Reserved", len=16, byte=4, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, value=0xe, id=true, },
	{ name="Reserved", len=3, byte=10, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="ORPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED ORWGENERATION", len=32, byte=20, bit=0, },
	{ name="NEW ORWGENERATION", len=32, byte=24, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="POPULATE TOKEN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x83, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x10, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=6, bit=0, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="PRE-FETCH (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x34, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="IMMED", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="PREFETCH LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="PRE-FETCH (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x90, },
	{ name="Reserved", len=1, byte=1, bit=0, reserved=true, },
	{ name="IMMED", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="PREFETCH LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="PREVENT ALLOW MEDIUM REMOVAL",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x1e, },
	{ name="Reserved", len=8, byte=1, bit=0, reserved=true, },
	{ name="Reserved", len=8, byte=2, bit=0, reserved=true, },
	{ name="Reserved", len=8, byte=3, bit=0, reserved=true, },
	{ name="PREVENT", len=2, byte=4, bit=0, nonzero=true, },
	{ name="Reserved", len=6, byte=4, bit=2, reserved=true, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="READ (6)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x08, },
	{ name="LOGICAL BLOCK ADDRESS", len=24, byte=1, bit=0, },
	{ name="TRANSFER LENGTH", len=8, byte=4, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="READ (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x28, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="RARC", len=1, byte=1, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="RDPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="READ (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa8, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="RARC", len=1, byte=1, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="RDPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=6, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=10, bit=0, nonzero=true, },
	{ name="Reserved", len=1, byte=10, bit=6, reserved=true, },
	{ name="Restricted for MMC-6", len=1, byte=10, bit=7, nonzero=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="READ (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x88, },
	{ name="DLD2", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="RARC", len=1, byte=1, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="RDPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="DLD0", len=1, byte=14, bit=6, nonzero=true, },
	{ name="DLD1", len=1, byte=14, bit=7, nonzero=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="READ (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0x9, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="Obsolete", len=1, byte=10, bit=1, obsolete=true, },
	{ name="RARC", len=1, byte=10, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="RDPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="READ CAPACITY (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x25, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="Obsolete", len=32, byte=2, bit=0, obsolete=true, },
	{ name="Reserved", len=16, byte=6, bit=0, reserved=true, },
	{ name="Obsolete", len=1, byte=8, bit=0, obsolete=true, },
	{ name="Reserved", len=7, byte=8, bit=1, reserved=true, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="READ CAPACITY (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x10, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Obsolete", len=64, byte=2, bit=0, obsolete=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="Obsolete", len=1, byte=14, bit=0, obsolete=true, },
	{ name="Reserved", len=7, byte=14, bit=1, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="READ DEFECT DATA (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x37, },
	{ name="Reserved", len=8, byte=1, bit=0, reserved=true, },
	{ name="DEFECT LIST FORMAT", len=3, byte=2, bit=0, nonzero=true, },
	{ name="REQ_GLIST", len=1, byte=2, bit=3, nonzero=true, },
	{ name="REQ_PLIST", len=1, byte=2, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=2, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=3, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="READ DEFECT DATA (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xb7, },
	{ name="DEFECT LIST FORMAT", len=3, byte=1, bit=0, nonzero=true, },
	{ name="REQ_GLIST", len=1, byte=1, bit=3, nonzero=true, },
	{ name="REQ_PLIST", len=1, byte=1, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="ADDRESS DESCRIPTOR INDEX", len=32, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="READ LONG (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3e, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="CORRCT", len=1, byte=1, bit=1, nonzero=true, },
	{ name="PBLOCK", len=1, byte=1, bit=2, nonzero=true, },
	{ name="Reserved", len=5, byte=1, bit=3, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="Reserved", len=8, byte=6, bit=0, reserved=true, },
	{ name="BYTE TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, bytes=9, bit=0, },
    },
    {
	name="READ LONG (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x11, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="Reserved", len=16, byte=10, bit=0, reserved=true, },
	{ name="BYTE TRANSFER LENGTH", byte=12, bit=0, nonzero=true, },
	{ name="CORRCT", len=1, byte=14, bit=0, nonzero=true, },
	{ name="PBLOCK", len=1, byte=14, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=14, bit=2, nonzero=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="REASSIGN BLOCKS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7, },
	{ name="LONGLIST", len=1, byte=1, bit=0, nonzero=true, },
	{ name="LONGLBA", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=6, byte=1, bit=2, reserved=true, },
	{ name="Reserved", len=24, byte=2, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="REPORT REFERRALS",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x13, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="ALLOCATION LENGTH", len=32, byte=10, bit=0, },
	{ name="ONE_SEG", len=1, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=14, bit=1, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="REPORT PROVISIONING INITIALZATION PATTERN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3a, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, value=0x1d, },
	{ name="Reserved", len=3, byte=1, bit=6, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="ALLOCATION LENGTH", len=32, byte=6, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="SANITIZE",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x48, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, },
	{ name="AUSE", len=1, byte=1, bit=5, nonzero=true, },
	{ name="ZNR", len=1, byte=1, bit=6, nonzero=true, },
	{ name="IMMED", len=1, byte=1, bit=7, nonzero=true, },
	{ name="Reserved", len=40, byte=2, bit=0, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="START STOP UNIT",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x1b, },
	{ name="IMMED", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="Reserved", len=8, byte=2, bit=0, reserved=true, },
	{ name="POWER CONDITION MODIFIER", len=4, byte=3, bit=0, nonzero=true, },
	{ name="Reserved", len=4, byte=3, bit=4, reserved=true, },
	{ name="START", len=1, byte=4, bit=0, nonzero=true, },
	{ name="LOEJ", len=1, byte=4, bit=1, nonzero=true, },
	{ name="NO_FLUSH", len=1, byte=4, bit=2, nonzero=true, },
	{ name="Reserved", len=1, byte=4, bit=3, reserved=true, },
	{ name="POWER CONDITION", len=4, byte=4, bit=4, nonzero=true, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="STREAM CONTROL",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9e, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x14, },
	{ name="STR_CTL", len=2, byte=1, bit=5, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=7, reserved=true, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="STR_ID", len=16, byte=4, bit=0, },
	{ name="Reserved", len=72, byte=6, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="SYNCHRONIZE CACHE (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x35, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="IMMED", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=2, obsolete=true, },
	{ name="Reserved", len=5, byte=1, bit=3, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="SYNCHRONIZE CACHE (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x91, },
	{ name="Reserved", len=1, byte=1, bit=0, reserved=true, },
	{ name="IMMED", len=1, byte=1, bit=1, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=2, obsolete=true, },
	{ name="Reserved", len=5, byte=1, bit=3, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="UNMAP",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x42, },
	{ name="ANCHOR", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Reserved", len=7, byte=1, bit=1, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="PARAMETER LIST LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="VERIFY (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x2f, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="VRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=1, byte=6, bit=6, reserved=true, },
	{ name="Restricted for MMC-6", len=1, byte=6, bit=7, nonzero=true, },
	{ name="VERIFICATION LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="VERIFY (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xaf, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="VRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="VERIFICATION LENGTH", len=32, byte=6, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=10, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=10, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="VERIFY (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8f, },
	{ name="Reserved", len=1, byte=1, bit=0, reserved=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="VRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="VERIFICATION LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="VERIFY (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0xa, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="BYTCHK", len=2, byte=10, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=10, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="VRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="VERIFICATION LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE (6)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x0a, },
	{ name="LOGICAL BLOCK ADDRESS", len=24, byte=1, bit=0, },
	{ name="TRANSFER LENGTH", len=8, byte=4, bit=0, },
	{ name="CONTROL", len=8, byte=5, bit=0, },
    },
    {
	name="WRITE (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x2a, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=1, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="WRITE (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xaa, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=1, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=6, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=10, bit=0, nonzero=true, },
	{ name="Reserved", len=1, byte=10, bit=6, reserved=true, },
	{ name="Restricted for MMC-6", len=1, byte=10, bit=7, nonzero=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="WRITE (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8a, },
	{ name="DLD2", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=1, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="DLD0", len=1, byte=14, bit=6, nonzero=true, },
	{ name="DLD1", len=1, byte=14, bit=7, nonzero=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0xb, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="Obsolete", len=1, byte=10, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=10, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE AND VERIFY (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x2e, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="WRITE AND VERIFY (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xae, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=6, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=10, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=10, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="WRITE AND VERIFY (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x8e, },
	{ name="Reserved", len=1, byte=1, bit=0, reserved=true, },
	{ name="BYTCHK", len=2, byte=1, bit=1, nonzero=true, },
	{ name="Reserved", len=1, byte=1, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE AND VERIFY (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0xc, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="BYTCHK", len=2, byte=10, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=10, bit=3, reserved=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE ATOMIC (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9c, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="ATOMIC BOUNDARY", len=16, byte=10, bit=0, },
	{ name="TRANSFER LENGTH", len=16, byte=12, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE ATOMIC (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="ATOMIC BOUNDARY", len=16, byte=4, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0xf, },
	{ name="Reserved", len=1, byte=10, bit=0, reserved=true, },
	{ name="Obsolete", len=1, byte=10, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=10, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE LONG (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x3f, },
	{ name="Obsolete", len=1, byte=1, bit=0, obsolete=true, },
	{ name="Reserved", len=4, byte=1, bit=1, reserved=true, },
	{ name="Obsolete", len=1, byte=1, bit=5, obsolete=true, },
	{ name="WR_UNCOR", len=1, byte=1, bit=6, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=7, obsolete=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="Reserved", len=8, byte=6, bit=0, reserved=true, },
	{ name="Obsolete", len=16, byte=7, bit=0, obsolete=true, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="WRITE LONG (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9f, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x11, },
	{ name="Obsolete", len=1, byte=1, bit=5, obsolete=true, },
	{ name="WR_UNCOR", len=1, byte=1, bit=6, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=7, obsolete=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="Reserved", len=16, byte=10, bit=0, reserved=true, },
	{ name="Obsolete", len=16, byte=12, bit=0, obsolete=true, },
	{ name="Reserved", len=8, byte=14, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE SAME (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x41, },
	{ name="Obsolete", len=3, byte=1, bit=0, obsolete=true, },
	{ name="UNMAP", len=1, byte=1, bit=3, nonzero=true, },
	{ name="ANCHOR", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="WRITE SAME (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x93, },
	{ name="NDOB", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=2, byte=1, bit=1, obsolete=true, },
	{ name="UNMAP", len=1, byte=1, bit=3, nonzero=true, },
	{ name="ANCHOR", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE SAME (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0xd, },
	{ name="NDOB", len=1, byte=10, bit=0, nonzero=true, },
	{ name="Obsolete", len=2, byte=10, bit=1, obsolete=true, },
	{ name="UNMAP", len=1, byte=10, bit=3, nonzero=true, },
	{ name="ANCHOR", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="NUMBER OF LOGICAL BLOCKS", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE STREAM (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x9a, },
	{ name="Reserved", len=3, byte=1, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=2, bit=0, },
	{ name="STR_ID", len=16, byte=10, bit=0, },
	{ name="TRANSFER LENGTH", len=16, byte=12, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="WRITE STREAM (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=16, byte=2, bit=0, reserved=true, },
	{ name="STR_ID", len=16, byte=4, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=5, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0x10, },
	{ name="Reserved", len=3, byte=10, bit=0, reserved=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="EXPECTED INITIAL LOGICAL BLOCK REFERENCE TAG", len=32, byte=20, bit=0, },
	{ name="EXPECTED LOGICAL BLOCK APPLICATION TAG", len=16, byte=24, bit=0, },
	{ name="LOGICAL BLOCK APPLICATION TAG MASK", len=16, byte=26, bit=0, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="WRITE USING TOKEN",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x83, },
	{ name="SERVICE ACTION", len=5, byte=1, bit=0, id=true, value=0x11, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="LIST IDENTIFIER", len=32, byte=6, bit=0, },
	{ name="PARAMETER LIST LENGTH", len=32, byte=10, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=14, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=14, bit=6, reserved=true, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="XDWRITEREAD (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x53, },
	{ name="XORPINFO", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="DISABLE WRITE", len=1, byte=1, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=1, bit=5, nonzero=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="XDWRITEREAD (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0x7, },
	{ name="XORPINFO", len=1, byte=10, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=10, bit=1, obsolete=true, },
	{ name="DISABLE WRITE", len=1, byte=10, bit=2, nonzero=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="WRPROTECT", len=3, byte=10, bit=5, nonzero=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="Reserved", len=64, byte=20, bit=0, reserved=true, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="XPWRITE (10)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x51, },
	{ name="XORPINFO", len=1, byte=1, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=1, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=1, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=1, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=1, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=1, bit=5, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=32, byte=2, bit=0, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="TRANSFER LENGTH", len=16, byte=7, bit=0, },
	{ name="CONTROL", len=8, byte=9, bit=0, },
    },
    {
	name="XPWRITE (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=32, byte=2, bit=0, reserved=true, },
	{ name="GROUP NUMBER", len=6, byte=6, bit=0, nonzero=true, },
	{ name="Reserved", len=2, byte=6, bit=6, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0x6, },
	{ name="XORPINFO", len=1, byte=10, bit=0, nonzero=true, },
	{ name="Obsolete", len=1, byte=10, bit=1, obsolete=true, },
	{ name="Reserved", len=1, byte=10, bit=2, reserved=true, },
	{ name="FUA", len=1, byte=10, bit=3, nonzero=true, },
	{ name="DPO", len=1, byte=10, bit=4, nonzero=true, },
	{ name="Reserved", len=3, byte=10, bit=5, reserved=true, },
	{ name="Reserved", len=8, byte=11, bit=0, reserved=true, },
	{ name="LOGICAL BLOCK ADDRESS", len=64, byte=12, bit=0, },
	{ name="Reserved", len=64, byte=20, bit=0, reserved=true, },
	{ name="TRANSFER LENGTH", len=32, byte=28, bit=0, },
    },
    {
	name="ATA PASS-THROUGH (12)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0xa1, },
	{ name="Reserved", len=1, byte=1, bit=0, reserved=true, },
	{ name="PROTOCOL", len=4, byte=1, bit=1, nonzero=true, },
	{ name="Obsolete", len=3, byte=1, bit=5, obsolete=true, },
	{ name="T_LENGTH", len=2, byte=2, bit=0, nonzero=true, },
	{ name="BYTE_BLOCK", len=1, byte=2, bit=2, nonzero=true, },
	{ name="T_DIR", len=1, byte=2, bit=3, nonzero=true, },
	{ name="T_TYPE", len=1, byte=2, bit=4, nonzero=true, },
	{ name="CK_COND", len=1, byte=2, bit=5, nonzero=true, },
	{ name="OFF_LINE", len=1, byte=2, bit=7, nonzero=true, },
	{ name="FEATURES (7:0)", len=8, byte=3, bit=0, },
	{ name="COUNT (7:0)", len=8, byte=4, bit=0, },
	{ name="LBA (7:0)", len=8, byte=5, bit=0, },
	{ name="LBA (15:8)", len=8, byte=6, bit=0, },
	{ name="LBA (23:16)", len=8, byte=7, bit=0, },
	{ name="DEVICE", len=8, byte=8, bit=0, },
	{ name="COMMAND", len=8, byte=9, bit=0, },
	{ name="Reserved", len=8, byte=10, bit=0, reserved=true, },
	{ name="CONTROL", len=8, byte=11, bit=0, },
    },
    {
	name="ATA PASS-THROUGH (16)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x85, },
	{ name="EXTEND", len=1, byte=1, bit=0, nonzero=true, },
	{ name="PROTOCOL", len=4, byte=1, bit=1, nonzero=true, },
	{ name="Obsolete", len=3, byte=1, bit=5, obsolete=true, },
	{ name="T_LENGTH", len=2, byte=2, bit=0, nonzero=true, },
	{ name="BYTE_BLOCK", len=1, byte=2, bit=2, nonzero=true, },
	{ name="T_DIR", len=1, byte=2, bit=3, nonzero=true, },
	{ name="T_TYPE", len=1, byte=2, bit=4, nonzero=true, },
	{ name="CK_COND", len=1, byte=2, bit=5, nonzero=true, },
	{ name="OFF_LINE", len=1, byte=2, bit=7, nonzero=true, },
	{ name="FEATURES (15:8)", len=8, byte=3, bit=0, },
	{ name="FEATURES (7:0)", len=8, byte=4, bit=0, },
	{ name="COUNT (15:8)", len=8, byte=5, bit=0, },
	{ name="COUNT (7:0)", len=8, byte=6, bit=0, },
	{ name="LBA (31:24)", len=8, byte=7, bit=0, },
	{ name="LBA (7:0)", len=8, byte=8, bit=0, },
	{ name="LBA (39:32)", len=8, byte=9, bit=0, },
	{ name="LBA (15:8)", len=8, byte=10, bit=0, },
	{ name="LBA (47:40)", len=8, byte=11, bit=0, },
	{ name="LBA (23:16)", len=8, byte=12, bit=0, },
	{ name="DEVICE", len=8, byte=13, bit=0, },
	{ name="COMMAND", len=8, byte=14, bit=0, },
	{ name="CONTROL", len=8, byte=15, bit=0, },
    },
    {
	name="ATA PASS-THROUGH (32)",
	{ name="OPERATION CODE", len=8, byte=0, bit=0, id=true, value=0x7f, },
	{ name="CONTROL", len=8, byte=1, bit=0, },
	{ name="Reserved", len=40, byte=2, bit=0, reserved=true, },
	{ name="ADDITIONAL CDB LENGTH", len=8, byte=7, bit=0, fixed=true, value=0x18, },
	{ name="SERVICE ACTION", len=16, byte=8, bit=0, id=true, value=0x1ff0, },
	{ name="EXTEND", len=1, byte=10, bit=0, nonzero=true, },
	{ name="PROTOCOL", len=4, byte=10, bit=1, nonzero=true, },
	{ name="Obsolete", len=3, byte=10, bit=5, obsolete=true, },
	{ name="T_LENGTH", len=2, byte=11, bit=0, nonzero=true, },
	{ name="BYTE_BLOCK", len=1, byte=11, bit=2, nonzero=true, },
	{ name="T_DIR", len=1, byte=11, bit=3, nonzero=true, },
	{ name="T_TYPE", len=1, byte=11, bit=4, nonzero=true, },
	{ name="CK_COND", len=1, byte=11, bit=5, nonzero=true, },
	{ name="OFF_LINE", len=1, byte=11, bit=7, nonzero=true, },
	{ name="Reserved", len=16, byte=12, bit=0, reserved=true, },
	{ name="LBA (47:40)", len=8, byte=14, bit=0, },
	{ name="LBA (39:32)", len=8, byte=15, bit=0, },
	{ name="LBA (31:24)", len=8, byte=16, bit=0, },
	{ name="LBA (23:16)", len=8, byte=17, bit=0, },
	{ name="LBA (15:8)", len=8, byte=18, bit=0, },
	{ name="LBA (7:0)", len=8, byte=19, bit=0, },
	{ name="FEATURES (15:8)", len=8, byte=20, bit=0, },
	{ name="FEATURES (7:0)", len=8, byte=21, bit=0, },
	{ name="COUNT (15:8)", len=8, byte=22, bit=0, },
	{ name="COUNT (7:0)", len=8, byte=23, bit=0, },
	{ name="DEVICE", len=8, byte=24, bit=0, },
	{ name="COMMAND", len=8, byte=25, bit=0, },
	{ name="Reserved", len=8, byte=26, bit=0, reserved=true, },
	{ name="ICC (7:0)", len=8, byte=27, bit=0, },
	{ name="AUXILIARY (31:24)", len=8, byte=28, bit=0, },
	{ name="AUXILIARY (23:16)", len=8, byte=29, bit=0, },
	{ name="AUXILIARY (15:8)", len=8, byte=30, bit=0, },
	{ name="AUXILIARY (7:0)", len=8, byte=31, bit=0, },
    },
}

return scsi_io
